-- MySQL Script generated by MySQL Workbench
-- 12/16/15 09:36:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
drop table if exists projettut.inscription;
drop table if exists projettut.autoriseModif;
drop table if exists projettut.agenda;
drop table if exists projettut.tarifs;
drop table if exists projettut.activite;
drop table if exists projettut.theme;
drop table if exists projettut.adulte;
drop table if exists projettut.enfant;
drop table if exists projettut.classe;
drop table if exists projettut.niveau;
drop table if exists projettut.ville;


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projettut
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projettut
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projettut` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `projettut` ;

-- -----------------------------------------------------
-- Table `projettut`.`niveau`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projettut`.`niveau` (
  `idNiveau` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `niveau` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idNiveau`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projettut`.`classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projettut`.`classe` (
  `idClasse` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nom` VARCHAR(45) NULL COMMENT '',
  `professeur` VARCHAR(45) NULL COMMENT '',
  `idNiveau` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idClasse`, `idNiveau`)  COMMENT '',
  INDEX `fk_classe_niveau1_idx` (`idNiveau` ASC)  COMMENT '',
  CONSTRAINT `fk_classe_niveau1`
    FOREIGN KEY (`idNiveau`)
    REFERENCES `projettut`.`niveau` (`idNiveau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projettut`.`enfant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projettut`.`enfant` (
  `idEnfant` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nomEnfant` VARCHAR(200) NULL COMMENT '',
  `prenomEnfant` VARCHAR(200) NULL COMMENT '',
  `dateDeNaissance` DATE NULL COMMENT '',
  `idClasse` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idEnfant`)  COMMENT '',
  INDEX `fk_enfant_classe1_idx` (`idClasse` ASC)  COMMENT '',
  CONSTRAINT `fk_enfant_classe1`
    FOREIGN KEY (`idClasse`)
    REFERENCES `projettut`.`classe` (`idClasse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projettut`.`theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projettut`.`theme` (
  `idTheme` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nomTheme` VARCHAR(200) NULL COMMENT '',
  PRIMARY KEY (`idTheme`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projettut`.`activite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projettut`.`activite` (
  `idActivite` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nomActivite` VARCHAR(200) NULL COMMENT '',
  `descriptionActivite` TEXT NULL COMMENT '',
  `idTheme` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idActivite`, `idTheme`)  COMMENT '',
  INDEX `fk_Activite_Theme?1_idx` (`idTheme` ASC)  COMMENT '',
  CONSTRAINT `fk_Activite_Theme?1`
    FOREIGN KEY (`idTheme`)
    REFERENCES `projettut`.`theme` (`idTheme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projettut`.`tarifs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projettut`.`tarifs` (
  `idTarif` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idActivite` INT NOT NULL COMMENT '',
  `tarifs` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idTarif`)  COMMENT '',
  INDEX `fk_Tarifs_Activite1_idx` (`idActivite` ASC)  COMMENT '',
  CONSTRAINT `fk_Tarifs_Activite1`
    FOREIGN KEY (`idActivite`)
    REFERENCES `projettut`.`activite` (`idActivite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projettut`.`inscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projettut`.`inscription` (
  `idEnfant` INT NOT NULL COMMENT '',
  `idActivite` INT NOT NULL COMMENT '',
  `dateDebutInscription` DATETIME NULL COMMENT '',
  `dateFinInscription` DATETIME NULL COMMENT '',
  `valideInscription` TINYINT(1) NULL COMMENT '',
  INDEX `fk_Enfant_has_Activite_Enfant1_idx` (`idEnfant` ASC)  COMMENT '',
  INDEX `fk_Inscription_Activite1_idx` (`idActivite` ASC)  COMMENT '',
  CONSTRAINT `fk_Enfant_has_Activite_Enfant1`
    FOREIGN KEY (`idEnfant`)
    REFERENCES `projettut`.`enfant` (`idEnfant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscription_Activite1`
    FOREIGN KEY (`idActivite`)
    REFERENCES `projettut`.`activite` (`idActivite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projettut`.`ville`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projettut`.`ville` (
  `idVille` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nomVille` VARCHAR(45) NULL COMMENT '',
  `codePostal` INT(5) NULL COMMENT '',
  PRIMARY KEY (`idVille`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projettut`.`adulte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projettut`.`adulte` (
  `idAdulte` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nom` VARCHAR(50) NULL COMMENT '',
  `prenom` VARCHAR(50) NULL COMMENT '',
  `idVille` INT NOT NULL COMMENT '',
  `login` VARCHAR(45) NULL COMMENT '',
  `motDePasse` VARCHAR(45) NULL COMMENT '',
  `adresseMail` VARCHAR(50) NULL COMMENT '',
  `rang` INT NULL COMMENT '',
  PRIMARY KEY (`idAdulte`)  COMMENT '',
  INDEX `fk_AdulteResponsable_Ville1_idx` (`idVille` ASC)  COMMENT '',
  CONSTRAINT `fk_AdulteResponsable_Ville1`
    FOREIGN KEY (`idVille`)
    REFERENCES `projettut`.`ville` (`idVille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projettut`.`autoriseModif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projettut`.`autoriseModif` (
  `idAdulteResponsable` INT NOT NULL COMMENT '',
  `idEnfant` INT NOT NULL COMMENT '',
  INDEX `fk_Enfant_has_AdulteResponsable_AdulteResponsable1_idx` (`idAdulteResponsable` ASC)  COMMENT '',
  INDEX `fk_Enfant_has_AdulteResponsable_Enfant1_idx` (`idEnfant` ASC)  COMMENT '',
  CONSTRAINT `fk_Enfant_has_AdulteResponsable_Enfant1`
    FOREIGN KEY (`idEnfant`)
    REFERENCES `projettut`.`enfant` (`idEnfant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enfant_has_AdulteResponsable_AdulteResponsable1`
    FOREIGN KEY (`idAdulteResponsable`)
    REFERENCES `projettut`.`adulte` (`idAdulte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projettut`.`agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projettut`.`agenda` (
  `idActivite` INT NOT NULL COMMENT '',
  `dateDebutActivite` DATETIME NULL COMMENT '',
  `dateFinActivite` DATETIME NULL COMMENT '',
  `jour` INT NULL COMMENT '',
  INDEX `fk_Agenda_Activite1_idx` (`idActivite` ASC)  COMMENT '',
  CONSTRAINT `fk_Agenda_Activite1`
    FOREIGN KEY (`idActivite`)
    REFERENCES `projettut`.`activite` (`idActivite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
